# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: XP Days 2016
email: info@xpday.net
description: > # this means to ignore newlines until "baseurl:"
  XP Day, Extreme Programming, Agile, XP, Extreme, Programming, Benelux, Belgium, The Netherlands
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://xpday.net" # the base hostname & protocol for your site
twitter_username: xpdaysbenelux
github_username:  xpdaysbenelux

# Build settings
markdown: kramdown
